### ISSUE TITLE
Creation of Documentation for Module 3

### ISSUE THREAD

**Issue by sergiosantano** [Arquisoft/Loader_i3b#10]
https://unioviedo-my.sharepoint.com/:w:/r/personal/uo251235_uniovi_es/_layouts/15/WopiFrame.aspx?sourcedoc=%7BDD31861E-EB9D-4247-9B41-3F720F3B92FE%7D&file=GESTUsers.2018.EN.docx&action=default&IsList=1&ListId=%7B296EC0E0-4A1C-429F-95A5-5396A08C1384%7D&ListItemId=55
The documentation for the third module must be created. We would have to:

- Write the new requirements **[Done]**
- Identify new stakeholders **[Done]**
- Identify new Quality Attributes **[Done]**
- Update the 5.1 List of Quality Attributes **[Done]**
- Identify new Constraints (if necessary) **[Done]**
- Modification of the table QA vs Stakeholders **[Done]**
- Edit the system scope and context **[Done]**
         - Create new BPMN diagram **[Done]**
         - Create new Business context diagram **[Done]**
- Modify quality scenarios **[Done]**
- Add the new view **[Work done in another issue]**

**Comment by sergiosantano** [comment]
New requirements for module 3 documented. Waiting for @JorgeGarciaMarin review

**Comment by sergiosantano** [comment]
New stakeholder identified and defined. Waiting for @JorgeGarciaMarin review

**Comment by sergiosantano** [comment]
New quality attributes detected:

**Testability**
  It must be testable that the incidents are loading correctly
  It must be testable that the management of incidents behaves as expected

**Usability**
  The creation of incidents must be simple and it mustn´t take too long.
  The management of incidents must be easy to learn and use by the operators.

**Simplicity**
  The four modules should be simple and easy to develop **[modified]**

**Comment by ghost** [comment]
In the  table QA vs Stakeholders, for those attributes who affect functionality that is documented by team I3B1 but that will be implemented by team I3B2, which are the interested stakeholders?
  I3B1?
  I3B2?
  Or both?
  Now I am assuming that is I3B1

**Comment by sergiosantano** [comment]
New quality attributes detected:

**Performance**
Loading incidences submitted by agents in the dashboard must be fast.

**Secutiry**
The system must keep the confidentiality of the incidences for the rest of agents.

**Scalability**
The system must have the ability to add new functionality at minimal effort.
