### ISSUE TITLE
Review and Correction the documentation of first delivery

### ISSUE THREAD

**Issue by sergiosantano** [Arquisoft/Loader_i3b#7]
Review all the errors detected by the teachers during the first delivery, detect that errors in the document and solve them
- Remove professor names **[Done]**
- 	Write a version **[Done]**
- 	Delete all optional task we are not going to implement. **[Waiting for review]** @sergiosantano 
- 	In pag 8 there is some lack of info.**[Done]**
- 	Stakeholders: divide 2 different stakeholders for students groups **[Done]**
- 	Improve resolution of the figures of vp. **[Done]** (our part)
- 	Quality scenarios , we have to add the constraints. Also to comment that some scenarios are not easy to reproduce. Section 9 add all the constraints to the views. In main overview put any kind of element to represent constraints. **[Another specific issue created]**
- 	Change the name of Agents List to Loader. **[Done]**
- 	Include "9.2.4 rational" in 9.1.3. **[Task of I3B2 group]**

**Comment by JorgeGarciaMarin** [comment]
https://docs.google.com/document/d/1YSAve5cs2w_nhPgeotslDH3BksxenMj56Ooyj8nMHOY/edit?usp=sharing

**Comment by ghost** [comment]
https://unioviedo-my.sharepoint.com/:w:/r/personal/uo251235_uniovi_es/_layouts/15/WopiFrame.aspx?sourcedoc=%7BDD31861E-EB9D-4247-9B41-3F720F3B92FE%7D&file=GESTUsers.2018.EN.docx&action=default&IsList=1&ListId=%7B296EC0E0-4A1C-429F-95A5-5396A08C1384%7D&ListItemId=55

**Comment by sergiosantano** [comment]
All reviews done
